//auth
export const AUTH_START = 'AUTH_START';
export const AUTH_ADMINSUCCESS = 'AUTH_ADMINSUCCESS';
export const AUTH_USERSUCCESS = 'AUTH_USERSUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH = 'AUTH';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_CHANGEROUTER = 'AUTH_CHANGEROUTER';


//user
export const USER_GET = 'USER_GET';

//timesheet
export const WEEK_DATE_GET = 'WEEK_DATE_GET';
export const CREATE_TIMESHEET_START = 'CREATE_TIMESHEET_START';
export const TIMESHEET_CREATE = 'TIMESHEET_CREATE';
export const TIMESHEET_CREATE_END = 'TIMESHEET_CREATE_END';

export const TIMESHEET_SHOW = 'TIMESHEET_SHOW';
export const TIMESHEET_SHOW_LOADING = 'TIMESHEET_SHOW_LOADING';

export const EDIT_TIMESHEET_MODE = 'EDIT_TIMESHEET_MODE';
export const EDIT_TIMESHEET = 'EDIT_TIMESHEET';
export const EDIT_CREATE_TIMESHEET = 'EDIT_CREATE_TIMESHEET';
export const SAVE_TIMESHEET = 'SAVE_TIMESHEET';
export const SAVE_TIMESHEET_END = 'SAVE_TIMESHEET_END';

export const CHANGE_INPUT_NUMBER_STATUS = 'CHANGE_INPUT_NUMBER_STATUS';

export const SET_SAVE_BUTTON = 'SET_SAVE_BUTTON';
export const SET_CREATE_BUTTON = 'SET_CREATE_BUTTON';

//Code
export const SET_Algorithm_BUTTON = 'SET_Algorithm_BUTTON';
export const SET_Home_BUTTON = 'SET_Home_BUTTON';
export const SET_BENCHMARK_BUTTON = 'SET_BENCHMARK_BUTTON';

